name: Hello World Action

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Create index.html
        run: echo "Hello World" > index.html
      - name: Run Python HTTP Server
        run: python -m http.server 8000 &
      - name: Print External IP
        run: curl ifconfig.me